import { StyleSheet } from 'react-native';
import { GOLD } from '../../lib/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  placeholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#111',
  },
  placeholderText: {
    color: '#fff',
    fontSize: 16,
    marginTop: 16,
  },
  tipsOverlay: {
    position: 'absolute',
    top: 80,
    left: 24,
    right: 24,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  tipText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
    marginBottom: 4,
    textAlign: 'center',
  },
  tipTextSecondary: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
    fontWeight: '400',
    marginBottom: 4,
    textAlign: 'center',
  },
  tipDismiss: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 12,
    marginTop: 4,
  },
  focusCard: {
    position: 'absolute',
    top: 80,
    left: 24,
    right: 24,
    backgroundColor: '#1A1A1C',
    borderRadius: 14,
    padding: 16,
  },
  focusTitle: {
    color: GOLD,
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  focusLabel: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 4,
  },
  focusCue: {
    color: '#999999',
    fontSize: 14,
    lineHeight: 20,
  },
  overlay: {
    position: 'absolute',
    bottom: 150,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  modeSegmentControl: {
    position: 'absolute',
    top: 60,
    left: 16,
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 20,
    padding: 3,
  },
  // Watch-primary pre-arm chip — same dark pill + left alignment as modeSegmentControl,
  // but pushed fully below the mode toggle (top:60 + ~34px pill height + 8px gap) so the
  // two never overlap in either the collapsed or expanded label state.
  preArmChip: {
    position: 'absolute',
    top: 102,
    left: 16,
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 20,
    padding: 3,
  },
  modeSegment: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 17,
  },
  modeSegmentActive: {
    backgroundColor: '#fff',
  },
  modeSegmentText: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.5)',
  },
  modeSegmentTextActive: {
    color: '#1a1a1a',
  },
  // Active-kid chip (top-right) — mirrors modeSegmentControl's dark pill for balance.
  kidChip: {
    position: 'absolute',
    top: 60,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    maxWidth: 160,
  },
  kidChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fff',
  },
  kidPickerBackdrop: {
    flex: 1,
  },
  kidPickerCard: {
    position: 'absolute',
    top: 100,
    right: 16,
    minWidth: 160,
    backgroundColor: 'rgba(20,20,20,0.96)',
    borderRadius: 14,
    paddingVertical: 4,
  },
  kidPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 8,
  },
  kidPickerDot: {
    fontSize: 12,
    width: 12,
  },
  kidPickerName: {
    flex: 1,
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  kidPickerHand: {
    color: '#999',
    fontSize: 12,
  },
  recordingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 24,
  },
  recordingText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  weakCaptureContainer: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.75)',
    paddingVertical: 20,
    paddingHorizontal: 28,
    borderRadius: 20,
  },
  weakCaptureText: {
    color: '#FFD060',
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  weakCaptureHint: {
    color: '#ccc',
    fontSize: 14,
    marginTop: 6,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 16,
    backgroundColor: GOLD,
    paddingVertical: 12,
    paddingHorizontal: 36,
    borderRadius: 24,
  },
  retryButtonText: {
    color: '#1A0E00',
    fontSize: 17,
    fontWeight: '700',
  },
  errorContainer: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 16,
  },
  errorText: {
    color: '#FF6B6B',
    fontSize: 17,
    fontWeight: '600',
    textAlign: 'center',
  },
  countdownOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  countdownText: {
    color: '#fff',
    fontSize: 120,
    fontWeight: '800',
    textShadowColor: 'rgba(0,0,0,0.6)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
  },
  cameraHintBanner: {
    position: 'absolute',
    top: 80,
    left: 24,
    right: 24,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  cameraHintText: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
});
